In [2]:
# 행렬 곱(dot product)
# np.dot(A,B)
# 만약 행과 열이 다르면 reshape 또는 전치행렬(transpose)를 사용하여 형 변환 후 실행
import numpy as np

#but, numpy에서는 크기가 다른 두 행렬 간에도 사칙연산(행렬 곱 제외)을 할 수 있는데
#이를 브로드캐스트(broadcast)라고 지칭함
#차원이 작은 쪽이 큰 쪽의 행 단위로 반복적으로 크기를 맞춘 후에 계산
A = np.array([[1, 2], [3, 4]])
B = np.array([4, 5])

print(A+B)
#[[5 7]
# [7 9]]

[[5 7]
 [7 9]]


In [5]:
#전치행렬

C = np.array([[1, 2], [3, 4], [5, 6]]) # 3x2행렬
D = C.T
print(D)
#[[1 3 5]
# [2 4 6]]

#벡터는 적용되지 않음, 벡터는 1차원이기 때문에 행과 열을 구분할 수 없음
#벡터의 경우 reshape으로 1행 5열이라고 규정해주고 전치해준다
E = np.array([1,2,3,4,5])
F = E.reshape(1, 5)
G = F.T
print(G)
#[[1]
# [2]
# [3]
# [4]
# [5]]

[[1 3 5]
 [2 4 6]]
[[1]
 [2]
 [3]
 [4]
 [5]]


In [9]:
#행렬 indexing / slicing

A = np.array([1, 2, 3, 4, 5, 6]).reshape(3,2)

print("A.shape ==", A.shape)
print(A)
#A.shape == (3, 2)
#[[1 2]
# [3 4]
# [5 6]]
 
print(A[0,0]) #1행1열 1
print(A[2,1]) #3행2열 6
print(A[0:-1, 1:2]) # [[20] [40]]
print(A[:, 0]) # [10 30 50]
print(A[:, :])
#[[1 2]
# [3 4]
# [5 6]]


A.shape == (3, 2)
[[1 2]
 [3 4]
 [5 6]]
1
6
[[2]
 [4]]
[1 3 5]
[[1 2]
 [3 4]
 [5 6]]


In [14]:
#iterator
#행렬 모든 원소에 접근하게 하는 기능

A = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])

print(A, '\n')
print("A.shape ==", A.shape, '\n')

#행렬 A의 iterator 생성

it = np.nditer(A, flags = ['multi_index'], op_flags = ['readwrite']) 

while not it.finished: #이터레이터가 finished 위치일 때까지 반복
               idx = it.multi_index
               print("current value ==> ", A[idx]) #10부터 80까지 차례대로 출력
               it.iternext() #이터레이터 다음 위치로 넘기기

[[10 20 30 40]
 [50 60 70 80]] 

A.shape == (2, 4) 

current value ==>  10
current value ==>  20
current value ==>  30
current value ==>  40
current value ==>  50
current value ==>  60
current value ==>  70
current value ==>  80
